
# CI jobs, basically to check that everything still compiles
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  basic_build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Install Arm GNU Toolchain (arm-none-eabi-gcc)
      uses: carlosperate/arm-none-eabi-gcc-action@v1
    
    - name: Install cmake
      uses: lukka/get-cmake@latest
      
    - name: build
      run: |
        cmake --preset Release
        cmake --build build/Release
  
